//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportGPSInfo
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "2.2.1.2648")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LogLocationSOAP", Namespace="http://www.ineventofemergency.com/wsdl/LocationLogging")]
    public partial class LogLocationService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        
        /// <remarks/>
        public LogLocationService()
        {
            this.Url = "http://www.ineventofemergency.com/loglocation/service/LogLocationPort";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PositionalLogEntryResponse", Namespace="http://www.ineventofemergency.com/schema/LocationLogging")]
        public PositionalLogEntryResponse LogLocation([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ineventofemergency.com/schema/LocationLogging")] PositionalLogEntryRequest PositionalLogEntryRequest)
        {
            object[] results = this.Invoke("LogLocation", new object[] {
                        PositionalLogEntryRequest});
            return ((PositionalLogEntryResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogLocation(PositionalLogEntryRequest PositionalLogEntryRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("LogLocation", new object[] {
                        PositionalLogEntryRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public PositionalLogEntryResponse EndLogLocation(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((PositionalLogEntryResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "2.2.1.2648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ineventofemergency.com/schema/LocationLogging")]
    public partial class PositionalLogEntryRequest
    {
        
        /// <remarks/>
        public Credentials Credentials;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LogEntry")]
        public PositionalLogEntry[] LogEntry;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Property", IsNullable=false)]
        public string[] Properties;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "2.2.1.2648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineventofemergency.com/schema/LocationLogging")]
    public partial class Credentials
    {
        
        /// <remarks/>
        public string UserID;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string AccessToken;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "2.2.1.2648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineventofemergency.com/schema/LocationLogging")]
    public partial class Coordinate
    {
        
        /// <remarks/>
        public string Latitude;
        
        /// <remarks/>
        public string Longitude;
        
        /// <remarks/>
        public CoordinateFormats Format;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "2.2.1.2648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineventofemergency.com/schema/LocationLogging")]
    public enum CoordinateFormats
    {
        
        /// <remarks/>
        DegreesDecimalMinutes,
        
        /// <remarks/>
        DecimalDegrees,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "2.2.1.2648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ineventofemergency.com/schema/LocationLogging")]
    public partial class PositionalLogEntry
    {
        
        /// <remarks/>
        public Coordinate Position;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime Time;
        
        /// <remarks/>
        public string TrackID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "2.2.1.2648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ineventofemergency.com/schema/LocationLogging")]
    public partial class PositionalLogEntryResponse
    {
        
        /// <remarks/>
        public string ReturnCode;
    }
}
